apiVersion: v2
name: linux-scanner
description: A Helm chart for deploying the Linux Hardening & Compliance Scanner on Kubernetes

type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - security
  - compliance
  - scanner
  - linux
  - hardening
  - cis
  - nist

home: https://github.com/add54/Linux-Hardening-Compliance-Scanner
sources:
  - https://github.com/add54/Linux-Hardening-Compliance-Scanner

maintainers:
  - name: Linux Security Team
    email: security@yourdomain.com

dependencies:
  - name: ingress-nginx
    version: "~4.0.0"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled

  - name: cert-manager
    version: "~1.0.0"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
